# Menus
menu:
  عنا: about
  وسوم: tags
  فئات: categories
  أرشيفات: archives
  الرئيسية: .

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.svg
    profile:
        enabled: false # Whether to show profile bar
        avatar: css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Yara3i
        author_title: Media production
        location: Algiers, Algeria
        follow: https://github.com/fellaga
    highlight: monokai
    sidebar: left # sidebar position, options: left, right or leave it empty
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: css/images/logo.png # path to favicon
    social_links:
        github: https://github.com/fellaga
        twitter: https://twitter.com/NotAFellaga
        facebook: https://facebook.com/NotAFellaga
    social_link_tooltip: true # enable the social link tooltip, options: true, false
    #change made for yara3i.
    fonts:
        url: fonts

# Widgets
widgets:
    - recent_posts
    #- category
    #- archive
    #- tag
    #- tagcloud
    #- links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: yara3i # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: #your github ID
        repo: #the repo to store comments
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: #your client ID
        client_secret: #your client secret

# Share
share: addtoany # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: UA-99603932-1 # enter the tracking ID for your Google Analytics
    google_site_verification: qc7xE6CyZfPklVvzSAk8b2afm4RP0Pf8mNtnR1lU7JU # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    mathjax: false # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
